# Generated by Django 5.0.2 on 2024-05-17 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_booking_vehicle_type_booking_vehicle'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
