# Generated by Django 5.0.2 on 2024-04-11 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_rename_locations_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='road_type',
            field=models.CharField(blank=True, choices=[('Highway', 'Highway'), ('Urban', 'Urban'), ('Rural', 'Rural'), ('Mountain', 'Mountain'), ('Off-road', 'Off-road')], max_length=20, null=True),
        ),
    ]
