# Generated by Django 5.0.2 on 2024-04-11 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_vehicle_road_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='drop_off_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drop_off_vehicles', to='inventory.location'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='pick_up_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pick_up_vehicles', to='inventory.location'),
        ),
    ]
