# Generated by Django 5.0.2 on 2024-04-11 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_vehicle_drop_off_location_vehicle_pick_up_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='drop_off_location',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='pick_up_location',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='road_type',
        ),
        migrations.CreateModel(
            name='RoadType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ManyToManyField(blank=True, choices=[('Highway', 'Highway'), ('Urban', 'Urban'), ('Rural', 'Rural'), ('Mountain', 'Mountain'), ('Off-road', 'Off-road')], to='inventory.roadtype')),
            ],
        ),
        migrations.AddField(
            model_name='vehicle',
            name='road_types',
            field=models.ManyToManyField(related_name='vehicles', to='inventory.roadtype'),
        ),
    ]
