# Generated by Django 5.0.2 on 2024-04-13 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_rename_price_vehicle_price_per_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadtype',
            name='name',
            field=models.CharField(choices=[('Highway', 'Highway'), ('Urban', 'Urban'), ('Rural', 'Rural'), ('Mountain', 'Mountain'), ('Off-road', 'Off-road'), ('Street', 'Street')], max_length=100),
        ),
    ]
