# Generated by Django 5.0.2 on 2024-04-13 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_roadtype_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicle_type',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='Seats',
            field=models.CharField(choices=[('automatic', 'Automatic'), ('manual', 'Manual')], default='4/5', max_length=100),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='Transmission',
            field=models.CharField(choices=[('automatic', 'Automatic'), ('manual', 'Manual')], default='automatic', max_length=100),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='Vehicle_Type',
            field=models.CharField(choices=[('automatic', 'Automatic'), ('manual', 'Manual')], default='hatchback', max_length=100),
        ),
    ]
