# Generated by Django 5.0.2 on 2024-04-13 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_remove_vehicle_vehicle_type_vehicle_seats_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='Seats',
            field=models.CharField(choices=[('4/5', '4/5'), ('6/10', '6/10')], default='4/5', max_length=100),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='Vehicle_Type',
            field=models.CharField(choices=[('hatchback', 'Hatchback'), ('sedan', 'Sedan'), ('suv', 'SUV'), ('muv', 'MUV'), ('minivan', 'Mini Van')], default='hatchback', max_length=100),
        ),
    ]
