# Generated by Django 5.0.2 on 2024-04-13 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_remove_vehicle_road_types_vehicle_road_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='model_year',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
