# Generated by Django 5.0.2 on 2024-04-25 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_vehicle_model_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='Road_Type',
            field=models.CharField(choices=[('Highway', 'Highway'), ('Rural', 'Rural'), ('Street', 'Street'), ('Off-road', 'Off-road')], default='Highway', max_length=100),
        ),
    ]
