# Generated by Django 5.0.2 on 2024-05-22 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='vehicle_name',
        ),
        migrations.AddField(
            model_name='booking',
            name='vehicle',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.vehicle'),
        ),
    ]
