# Generated by Django 5.0.2 on 2024-05-22 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_remove_booking_vehicle_name_booking_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='purchase_order_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
