# Generated by Django 5.0.2 on 2024-05-22 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_booking_purchase_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cost',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
